CREATE TABLE SPELL_INFO (
	SPELL_NO	NUMBER		NOT NULL,
	SPELL_NAME	VARCHAR(20)		NULL,
	SPELL_INFO	VARCHAR(200)		NULL
);

COMMENT ON COLUMN SPELL_INFO.SPELL_NO IS '주문 번호(시퀀스 자동생성)';

COMMENT ON COLUMN SPELL_INFO.SPELL_NAME IS '주문 이름';

COMMENT ON COLUMN SPELL_INFO.SPELL_INFO IS '주문 설명';

CREATE TABLE BOARD_LIKES (
	USER_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN BOARD_LIKES.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN BOARD_LIKES.BOARD_NO IS '시퀀스 자동생성';

CREATE TABLE LOL_ITEM_INFO (
	ITEM_NO	NUMBER		NOT NULL,
	ITEM_NAME	VARCHAR(20)		NOT NULL,
	ITEM_PRICE	NUMBER		NOT NULL,
	ITEM_INFO	VARCHAR(200)		NULL,
	ITEM_IMG	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_NO IS '아이템 번호(시퀀스 자동생성)';

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_NAME IS '아이템 이름';

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_PRICE IS '아이템 가격';

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_INFO IS '아이템 설명';

COMMENT ON COLUMN LOL_ITEM_INFO.ITEM_IMG IS '아이템 이미지';

CREATE TABLE BOARD (
	BOARD_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	CATEGORY_NO	VARCHAR(255)		NOT NULL,
	GAME_CODE	VARCHAR(10)		NOT NULL,
	BOARD_TITLE	NVARCHAR(50)		NOT NULL,
	BOARD_CONTENT	NVARCHAR(500)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	BOARD_CD	CHAR(1)	DEFAULT Y	NOT NULL,
	READ_COUNT	NUMBER		NOT NULL
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN BOARD.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN BOARD.CATEGORY_NO IS '자유 , 공략';

COMMENT ON COLUMN BOARD.GAME_CODE IS 'LOL,OW,BG';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글 제목';

COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글 내용';

COMMENT ON COLUMN BOARD.POST_DATE IS '글 작성시간';

COMMENT ON COLUMN BOARD.BOARD_CD IS '글 삭제여부';

COMMENT ON COLUMN BOARD.READ_COUNT IS '글 조회수';

CREATE TABLE PATCHNOTE (
	PATCHNOTE_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR2(10)		NOT NULL,
	TITLE	VARCHAR(100)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	PATCHNOTE_CONTENT	VARCHAR2(2000)		NOT NULL
);

COMMENT ON COLUMN PATCHNOTE.PATCHNOTE_NO IS '시퀀스자동생성';

COMMENT ON COLUMN PATCHNOTE.GAME_CODE IS 'LOL,OW,BG';

COMMENT ON COLUMN PATCHNOTE.TITLE IS '글 번호';

COMMENT ON COLUMN PATCHNOTE.POST_DATE IS '디폴트 : SYSDATE';

COMMENT ON COLUMN PATCHNOTE.PATCHNOTE_CONTENT IS '패치노트 내용';

CREATE TABLE REPLY (
	REPLY_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	REPLY_CONTENT	NVARCHAR(200)		NOT NULL,
	REPLY_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	CHAR(1)	DEFAULT Y	NOT NULL,
	PARENT_REPLY_NO	NUMBER		NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPLY.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '글 내용';

COMMENT ON COLUMN REPLY.REPLY_DATE IS '댓글 작성시간';

COMMENT ON COLUMN REPLY.STATUS IS '댓글 삭제여부';

COMMENT ON COLUMN REPLY.PARENT_REPLY_NO IS '대댓글 구현';

CREATE TABLE MARKER_CATEGORY (
	CATEGORY_NO	NUMBER		NOT NULL,
	CATEGORY_NAME	VARCHAR2(100)		NOT NULL
);

CREATE TABLE WEAPON (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_DAMAGE	NUMBER		NOT NULL,
	ITEM_AMMO_COUNT	NUMBER		NOT NULL,
	ITEM_AMMO_TYPE	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN WEAPON.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';

CREATE TABLE NOTICE (
	NOTICE_NO	NUMBER		NOT NULL,
	TITLE	VARCHAR(100)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	NOTICE_CONTENT	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN NOTICE.TITLE IS '글 제목';

COMMENT ON COLUMN NOTICE.POST_DATE IS '디폴트 : SYSDATE';

COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지사항 내용';

CREATE TABLE ITEM_LOG (
	LOG_NO	NUBMER		NOT NULL,
	ITEM_NO	NUMBER		NOT NULL,
	BOX_NO	NUMBER		NOT NULL
);

CREATE TABLE LOG_GG_USER (
	USER_NO	NUMBER		NOT NULL,
	USER_ID	VARCHAR(20)		NOT NULL,
	USER_PW	NVARCHAR(50)		NOT NULL,
	USER_NAME	VARCHAR2		NOT NULL,
	STATUS	CHAR(1)	DEFAULT Y	NOT NULL,
	WITHDRAW	bit(1)		NOT NULL,
	ENROLL_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	USER_ROLE	CHAR(1)	DEFAULT U	NOT NULL
);

COMMENT ON COLUMN LOG_GG_USER.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN LOG_GG_USER.USER_ID IS '아이디';

COMMENT ON COLUMN LOG_GG_USER.USER_PW IS '비밀번호';

COMMENT ON COLUMN LOG_GG_USER.USER_NAME IS '닉네임';

COMMENT ON COLUMN LOG_GG_USER.STATUS IS '로그인 Y , N';

COMMENT ON COLUMN LOG_GG_USER.WITHDRAW IS '탈퇴여부';

COMMENT ON COLUMN LOG_GG_USER.ENROLL_DATE IS '디폴트 : SYSDATE';

COMMENT ON COLUMN LOG_GG_USER.USER_ROLE IS '회원(U), 관리자(A)';

CREATE TABLE CHAMP_INFO (
	CHAMP_NO	NUMBER		NOT NULL,
	CHAMP_NAME	VARCHAR(20)		NOT NULL,
	CHAMP_POSITION	VARCHAR(10)		NOT NULL,
	CHAMP_ROLES	VARCHAR(10)		NULL,
	CHAMP_IMG	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN CHAMP_INFO.CHAMP_NO IS '챔피언 번호(시퀀스 자동생성)';

COMMENT ON COLUMN CHAMP_INFO.CHAMP_NAME IS '챔피언 이름';

COMMENT ON COLUMN CHAMP_INFO.CHAMP_POSITION IS '챔피언 역할군(암살자,원거리 딜러, 탱커 등)';

COMMENT ON COLUMN CHAMP_INFO.CHAMP_ROLES IS '탑,정글,미드,원딜,서폿';

COMMENT ON COLUMN CHAMP_INFO.CHAMP_IMG IS '챔피언 이미지';

CREATE TABLE PARENT_REPLY (
	USER_NAME	VARCHAR2		NOT NULL,
	REPLY_CONTENT	NVARCHAR(200)		NOT NULL,
	REPLY_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	STATUS	CHAR(1)	DEFAULT Y	NOT NULL
);

COMMENT ON COLUMN PARENT_REPLY.USER_NAME IS '닉네임';

COMMENT ON COLUMN PARENT_REPLY.REPLY_CONTENT IS '글 내용';

COMMENT ON COLUMN PARENT_REPLY.REPLY_DATE IS '댓글 작성시간';

COMMENT ON COLUMN PARENT_REPLY.STATUS IS '댓글 삭제여부';

CREATE TABLE OW_BOARD (
	TITLE	NVARCHAR(50)		NOT NULL,
	STATUS	CHAR(1)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN OW_BOARD.TITLE IS '제목';

COMMENT ON COLUMN OW_BOARD.STATUS IS '글 삭제 유무';

COMMENT ON COLUMN OW_BOARD.POST_DATE IS '디폴트 : SYSDATE';

CREATE TABLE CHAMP_SKIN_INFO (
	CHAMP_SKIN_NO	NUMBER		NOT NULL,
	CHAMP_NO	NUMBER		NOT NULL,
	CHAMP_SKIN_NAME	VARCHAR(20)		NOT NULL,
	CHAMP_SKIN_IMG	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_NO IS '스킨 번호(시퀀스 자동생성)';

COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_NO IS '챔피언 번호(시퀀스 자동생성)';

COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_NAME IS '챔피언 스킨 이름';

COMMENT ON COLUMN CHAMP_SKIN_INFO.CHAMP_SKIN_IMG IS '챔피언 이미지';

CREATE TABLE ATTACH_FILE (
	FILE_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR(10)		NOT NULL,
	ORIGIN_NAME	VARCHAR2(255)		NOT NULL,
	CHANGE_NAME	VARCHAR2(255)		NOT NULL,
	FILE_PATH	VARCHAR2(500)		NOT NULL,
	FILE_EXT	VARCHAR2(50)		NOT NULL,
	FILE_SIZE	NUMBER		NOT NULL
);

COMMENT ON COLUMN ATTACH_FILE.BOARD_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN ATTACH_FILE.GAME_CODE IS 'LOL,OW,BG';

COMMENT ON COLUMN ATTACH_FILE.ORIGIN_NAME IS '첨부파일 원본 이름';

CREATE TABLE ITEM_WEIGHT (
	ITEM_NO	NUMBER		NOT NULL,
	BOX_NO	NUMBER		NOT NULL,
	WEIGHT	NUMBER		NOT NULL
);

CREATE TABLE MAP_MARKER (
	MARKER_NO	NUMBER		NOT NULL,
	COORD_X	NUMBER		NOT NULL,
	COORD_Y	NUMBER		NOT NULL,
	MARKER_IMG	VARCHAR2(500)		NOT NULL,
	MAP_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL
);

CREATE TABLE HERO_INFO (
	HERO_NO	NUMBER		NOT NULL,
	HERO_NAME	VARCHAR(20)		NOT NULL,
	HERO_INTRO	VARCHAR(100)		NULL,
	HERO_HP	NUMBER	DEFAULT 0	NOT NULL,
	HERO_POSITION	VARCHAR(10)		NOT NULL
);

COMMENT ON COLUMN HERO_INFO.HERO_NO IS '영웅 번호(시퀀스 자동생성)';

COMMENT ON COLUMN HERO_INFO.HERO_NAME IS '영웅 이름';

COMMENT ON COLUMN HERO_INFO.HERO_INTRO IS '영웅 소개';

COMMENT ON COLUMN HERO_INFO.HERO_HP IS '영웅 HP';

COMMENT ON COLUMN HERO_INFO.HERO_POSITION IS '영웅 포지션(힐러,딜러,탱커 등)';

CREATE TABLE PARTY_RECRUIT (
	BOARD_NO	NUMBER		NOT NULL,
	CAPACITY	NUMBER		NOT NULL,
	TIER	VARCHAR2(10)		NOT NULL,
	CURRENT	VARCHAR2(10)		NOT NULL,
	PREFER_MAP	VARCHAR2(20)	DEFAULT 해당 없음	NOT NULL
);

COMMENT ON COLUMN PARTY_RECRUIT.BOARD_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN PARTY_RECRUIT.CAPACITY IS '모집 인원수';

COMMENT ON COLUMN PARTY_RECRUIT.TIER IS '티어';

COMMENT ON COLUMN PARTY_RECRUIT.CURRENT IS '모집 중 , 모집완료';

COMMENT ON COLUMN PARTY_RECRUIT.PREFER_MAP IS '선호 맵';

CREATE TABLE BG_BOARD (
	TITLE	NVARCHAR(50)		NOT NULL,
	STATUS	CHAR(1)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN BG_BOARD.TITLE IS '제목';

COMMENT ON COLUMN BG_BOARD.STATUS IS '글 삭제 유무';

COMMENT ON COLUMN BG_BOARD.POST_DATE IS '디폴트 : SYSDATE';

CREATE TABLE CopyOfRUNE_INFO (
	TALENT_NO	NUMBER		NOT NULL,
	RUNE_NO	NUMBER		NOT NULL,
	TALENT_NAME	VARCHAR(10)		NOT NULL,
	TALENT_INFO	VARCHAR(100)		NULL,
	TALENT_IMG	VARCHAR(200)		NULL
);

COMMENT ON COLUMN CopyOfRUNE_INFO.TALENT_NO IS '특성 번호(시퀀스 자동생성)';

COMMENT ON COLUMN CopyOfRUNE_INFO.RUNE_NO IS '룬 번호(시퀀스 자동생성)';

COMMENT ON COLUMN CopyOfRUNE_INFO.TALENT_NAME IS '특성 이름';

COMMENT ON COLUMN CopyOfRUNE_INFO.TALENT_INFO IS '특성 설명';

COMMENT ON COLUMN CopyOfRUNE_INFO.TALENT_IMG IS '특성 이미지';

CREATE TABLE == (

);

CREATE TABLE BAG_ITEM_INFO (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_NAME	VARCHAR(20)		NOT NULL,
	ITEM_INFO	VARCHAR(200)		NULL,
	ITEM_IMG	VARCHAR2(500)		NULL,
	ITEM_TYPE	VARCHAT2(50)		NOT NULL
);

COMMENT ON COLUMN BAG_ITEM_INFO.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';

COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_NAME IS '아이템 이름';

COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_INFO IS '아이템 설명';

COMMENT ON COLUMN BAG_ITEM_INFO.ITEM_IMG IS '아이템 이미지';

CREATE TABLE EQUIPMENT (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	ITEM_DURABILITY	NUMBER		NULL,
	ITEM_DAMAGE_REDUCTION	NUMBER		NULL
);

COMMENT ON COLUMN EQUIPMENT.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';

CREATE TABLE MAP_INFO (
	MAP_NO	NUMBER		NOT NULL,
	MAP_NAME	VARCHAR2(50)		NOT NULL,
	MAP_IMG	VARCHAR2(500)		NOT NULL
);

CREATE TABLE RUNE_INFO (
	RUNE_NO	NUMBER		NOT NULL,
	RUNE_NAME	VARCHAR(10)		NOT NULL,
	RUNE_INFO	VARCHAR(50)		NULL,
	RUNE_IMG	VARCHAR(200)		NULL
);

COMMENT ON COLUMN RUNE_INFO.RUNE_NO IS '룬 번호(시퀀스 자동생성)';

COMMENT ON COLUMN RUNE_INFO.RUNE_NAME IS '룬 이름';

COMMENT ON COLUMN RUNE_INFO.RUNE_INFO IS '룬 설명';

COMMENT ON COLUMN RUNE_INFO.RUNE_IMG IS '룬 이미지';

CREATE TABLE ITEM_COMPATIBILITY (
	ITEM_NO	NUMBER		NOT NULL,
	CATEGORY_NO	NUMBER		NOT NULL,
	PART_ITEM_NO	NUMBER		NOT NULL,
	PART_CATEGORY_NO	NUMBER		NOT NULL,
	WEAPON_ITEM_NO	NUMBER		NOT NULL,
	WEAPON_CATEGORY_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN ITEM_COMPATIBILITY.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';

CREATE TABLE Box_LIST (
	BOX_NO	NUMBER		NOT NULL,
	BOX_NAME	VARCHAR2(100)		NOT NULL,
	BOX_TYPE	VARCHAR2(100)		NOT NULL,
	START_DATE	DATE		NOT NULL,
	END_DATE	DATE		NOT NULL
);

COMMENT ON COLUMN Box_LIST.START_DATE IS '뽑기 기간 시작일';

COMMENT ON COLUMN Box_LIST.END_DATE IS '종료일';

CREATE TABLE \ (
	LIKE_COUNT	NUMBER		NOT NULL
);

COMMENT ON COLUMN \.LIKE_COUNT IS '받은 공감 수';

CREATE TABLE HERO_SKIN_INFO (
	HERO_SKIN_NO	NUMBER		NOT NULL,
	HERO_NO	NUMBER		NOT NULL,
	HERO_SKIN_NAME	VARCHAR(20)		NOT NULL,
	HERO_SKIN_IMG	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_NO IS '스킨 번호(시퀀스 자동생성)';

COMMENT ON COLUMN HERO_SKIN_INFO.HERO_NO IS '영웅 번호(시퀀스 자동생성)';

COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_NAME IS '챔피언 스킨 이름';

COMMENT ON COLUMN HERO_SKIN_INFO.HERO_SKIN_IMG IS '챔피언 이미지';

CREATE TABLE LOL_BOARD (
	TITLE	NVARCHAR(50)		NOT NULL,
	STATUS	CHAR(1)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN LOL_BOARD.TITLE IS '제목';

COMMENT ON COLUMN LOL_BOARD.STATUS IS '글 삭제 유무';

COMMENT ON COLUMN LOL_BOARD.POST_DATE IS '디폴트 : SYSDATE';

CREATE TABLE REPORT (
	REPORT_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NULL,
	REPLY_NO	NUMBER		NULL,
	CONTENT	VARCHAR2(2000)		NOT NULL,
	STATUS	CHAR(1)		NOT NULL,
	DONE_DATE	DATE	DEFAULT SYSDATE	NULL,
	REPORT_TYPE	VARCHAR(10)		NOT NULL
);

COMMENT ON COLUMN REPORT.REPORT_NO IS '신고 글 번호';

COMMENT ON COLUMN REPORT.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPORT.BOARD_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPORT.REPLY_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPORT.CONTENT IS '신고 내용';

COMMENT ON COLUMN REPORT.STATUS IS 'Y or N';

COMMENT ON COLUMN REPORT.DONE_DATE IS '처리완료시간';

COMMENT ON COLUMN REPORT.REPORT_TYPE IS '글,댓글,유저';

CREATE TABLE INQUIRY (
	BOARD_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL,
	USER_NAME	VARCHAR2		NOT NULL,
	BOARD_CONTENT	NVARCHAR(500)		NOT NULL,
	BOARD_TITLE	NVARCHAR(50)		NOT NULL,
	POST_DATE	DATE	DEFAULT SYSDATE	NOT NULL,
	ANSWER_STATUS	CHAR(1)	DEFAULT W	NOT NULL,
	REASON	VARCHAR2(20)		NOT NULL,
	ANSWER	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN INQUIRY.BOARD_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN INQUIRY.USER_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN INQUIRY.USER_NAME IS '닉네임';

COMMENT ON COLUMN INQUIRY.BOARD_CONTENT IS '글 내용';

COMMENT ON COLUMN INQUIRY.BOARD_TITLE IS '글 제목';

COMMENT ON COLUMN INQUIRY.POST_DATE IS '글 작성시간';

COMMENT ON COLUMN INQUIRY.ANSWER_STATUS IS '답변대기(W), 답변완료(C)';

COMMENT ON COLUMN INQUIRY.REASON IS '문의사유';

COMMENT ON COLUMN INQUIRY.ANSWER IS '관리자의 답변 내용';

CREATE TABLE GAME_CODE (
	GAME_CODE	VARCHAR(10)		NOT NULL,
	GAME_NAME	VARCHAR(50)		NOT NULL
);

COMMENT ON COLUMN GAME_CODE.GAME_CODE IS 'LOL,OW,BG';

CREATE TABLE ITEM_LIST (
	ITEM_NO	NUMBER		NOT NULL,
	ITEM_NAME	VARCHAR2(100)		NOT NULL,
	ITEM_GRADE	VARCHAR2(20)		NOT NULL,
	ITEM_TYPE	VARCHAR2(50)		NOT NULL
);

CREATE TABLE CATEGORY_TABLE (
	CATEGORY_NO	NUMBER		NOT NULL,
	GAME_CODE	VARCHAR(10)		NOT NULL,
	CATEGORY_NAME	VARCHAR(50)		NOT NULL,
	PARENT_CATEGORY_NO	NUMBER		NULL
);

COMMENT ON COLUMN CATEGORY_TABLE.CATEGORY_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN CATEGORY_TABLE.GAME_CODE IS 'LOL,OW,BG';

COMMENT ON COLUMN CATEGORY_TABLE.CATEGORY_NAME IS '자유 게시판, 공략 게시판';

COMMENT ON COLUMN CATEGORY_TABLE.PARENT_CATEGORY_NO IS 'ex) 게시판 -> 자유, 공략 게시판';

CREATE TABLE BAG_ITEM_CATEGORY (
	CATEGORY_NO	NUMBER		NOT NULL,
	CATEGORY_NAME	VARCHAR2(100)		NOT NULL,
	CATEGORY_IMG	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN BAG_ITEM_CATEGORY.CATEGORY_NO IS '1(무기), 2(부착물), 3(탄약),, 4(방어구), 5(소모품)';

CREATE TABLE REPLY_LIKES (
	REPLY_NO	NUMBER		NOT NULL,
	USER_NO	NUMBER		NOT NULL
);

COMMENT ON COLUMN REPLY_LIKES.REPLY_NO IS '시퀀스 자동생성';

COMMENT ON COLUMN REPLY_LIKES.USER_NO IS '시퀀스 자동생성';

ALTER TABLE SPELL_INFO ADD CONSTRAINT PK_SPELL_INFO PRIMARY KEY (
	SPELL_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT PK_BOARD_LIKES PRIMARY KEY (
	USER_NO,
	BOARD_NO
);

ALTER TABLE LOL_ITEM_INFO ADD CONSTRAINT PK_LOL_ITEM_INFO PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE PATCHNOTE ADD CONSTRAINT PK_PATCHNOTE PRIMARY KEY (
	PATCHNOTE_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO
);

ALTER TABLE MARKER_CATEGORY ADD CONSTRAINT PK_MARKER_CATEGORY PRIMARY KEY (
	CATEGORY_NO
);

ALTER TABLE WEAPON ADD CONSTRAINT PK_WEAPON PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NOTICE_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT PK_ITEM_LOG PRIMARY KEY (
	LOG_NO
);

ALTER TABLE LOG_GG_USER ADD CONSTRAINT PK_LOG_GG_USER PRIMARY KEY (
	USER_NO
);

ALTER TABLE CHAMP_INFO ADD CONSTRAINT PK_CHAMP_INFO PRIMARY KEY (
	CHAMP_NO
);

ALTER TABLE CHAMP_SKIN_INFO ADD CONSTRAINT PK_CHAMP_SKIN_INFO PRIMARY KEY (
	CHAMP_SKIN_NO,
	CHAMP_NO
);

ALTER TABLE ATTACH_FILE ADD CONSTRAINT PK_ATTACH_FILE PRIMARY KEY (
	FILE_NO
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT PK_ITEM_WEIGHT PRIMARY KEY (
	ITEM_NO,
	BOX_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT PK_MAP_MARKER PRIMARY KEY (
	MARKER_NO
);

ALTER TABLE HERO_INFO ADD CONSTRAINT PK_HERO_INFO PRIMARY KEY (
	HERO_NO
);

ALTER TABLE PARTY_RECRUIT ADD CONSTRAINT PK_PARTY_RECRUIT PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE CopyOfRUNE_INFO ADD CONSTRAINT PK_COPYOFRUNE_INFO PRIMARY KEY (
	TALENT_NO,
	RUNE_NO
);

ALTER TABLE BAG_ITEM_INFO ADD CONSTRAINT PK_BAG_ITEM_INFO PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (
	ITEM_NO,
	CATEGORY_NO
);

ALTER TABLE MAP_INFO ADD CONSTRAINT PK_MAP_INFO PRIMARY KEY (
	MAP_NO
);

ALTER TABLE RUNE_INFO ADD CONSTRAINT PK_RUNE_INFO PRIMARY KEY (
	RUNE_NO
);

ALTER TABLE Box_LIST ADD CONSTRAINT PK_BOX_LIST PRIMARY KEY (
	BOX_NO
);

ALTER TABLE HERO_SKIN_INFO ADD CONSTRAINT PK_HERO_SKIN_INFO PRIMARY KEY (
	HERO_SKIN_NO,
	HERO_NO
);

ALTER TABLE REPORT ADD CONSTRAINT PK_REPORT PRIMARY KEY (
	REPORT_NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT PK_INQUIRY PRIMARY KEY (
	BOARD_NO
);

ALTER TABLE GAME_CODE ADD CONSTRAINT PK_GAME_CODE PRIMARY KEY (
	GAME_CODE
);

ALTER TABLE ITEM_LIST ADD CONSTRAINT PK_ITEM_LIST PRIMARY KEY (
	ITEM_NO
);

ALTER TABLE CATEGORY_TABLE ADD CONSTRAINT PK_CATEGORY_TABLE PRIMARY KEY (
	CATEGORY_NO,
	GAME_CODE
);

ALTER TABLE BAG_ITEM_CATEGORY ADD CONSTRAINT PK_BAG_ITEM_CATEGORY PRIMARY KEY (
	CATEGORY_NO
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT PK_REPLY_LIKES PRIMARY KEY (
	REPLY_NO,
	USER_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT FK_LOG_GG_USER_TO_BOARD_LIKES_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE BOARD_LIKES ADD CONSTRAINT FK_BOARD_TO_BOARD_LIKES_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_LOG_GG_USER_TO_BOARD_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_CATEGORY_TABLE_TO_BOARD_1 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES CATEGORY_TABLE (
	CATEGORY_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_CATEGORY_TABLE_TO_BOARD_2 FOREIGN KEY (
	GAME_CODE
)
REFERENCES CATEGORY_TABLE (
	GAME_CODE
);

ALTER TABLE PATCHNOTE ADD CONSTRAINT FK_GAME_CODE_TO_PATCHNOTE_1 FOREIGN KEY (
	GAME_CODE
)
REFERENCES GAME_CODE (
	GAME_CODE
);

ALTER TABLE REPLY ADD CONSTRAINT FK_LOG_GG_USER_TO_REPLY_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE WEAPON ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_WEAPON_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO
);

ALTER TABLE WEAPON ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_WEAPON_2 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	CATEGORY_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT FK_ITEM_LIST_TO_ITEM_LOG_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES ITEM_LIST (
	ITEM_NO
);

ALTER TABLE ITEM_LOG ADD CONSTRAINT FK_Box_LIST_TO_ITEM_LOG_1 FOREIGN KEY (
	BOX_NO
)
REFERENCES Box_LIST (
	BOX_NO
);

ALTER TABLE CHAMP_SKIN_INFO ADD CONSTRAINT FK_CHAMP_INFO_TO_CHAMP_SKIN_INFO_1 FOREIGN KEY (
	CHAMP_NO
)
REFERENCES CHAMP_INFO (
	CHAMP_NO
);

ALTER TABLE ATTACH_FILE ADD CONSTRAINT FK_BOARD_TO_ATTACH_FILE_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE ATTACH_FILE ADD CONSTRAINT FK_BOARD_TO_ATTACH_FILE_2 FOREIGN KEY (
	GAME_CODE
)
REFERENCES BOARD (
	GAME_CODE
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT FK_ITEM_LIST_TO_ITEM_WEIGHT_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES ITEM_LIST (
	ITEM_NO
);

ALTER TABLE ITEM_WEIGHT ADD CONSTRAINT FK_Box_LIST_TO_ITEM_WEIGHT_1 FOREIGN KEY (
	BOX_NO
)
REFERENCES Box_LIST (
	BOX_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT FK_MAP_INFO_TO_MAP_MARKER_1 FOREIGN KEY (
	MAP_NO
)
REFERENCES MAP_INFO (
	MAP_NO
);

ALTER TABLE MAP_MARKER ADD CONSTRAINT FK_MARKER_CATEGORY_TO_MAP_MARKER_1 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES MARKER_CATEGORY (
	CATEGORY_NO
);

ALTER TABLE PARTY_RECRUIT ADD CONSTRAINT FK_BOARD_TO_PARTY_RECRUIT_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE CopyOfRUNE_INFO ADD CONSTRAINT FK_RUNE_INFO_TO_CopyOfRUNE_INFO_1 FOREIGN KEY (
	RUNE_NO
)
REFERENCES RUNE_INFO (
	RUNE_NO
);

ALTER TABLE BAG_ITEM_INFO ADD CONSTRAINT FK_BAG_ITEM_CATEGORY_TO_BAG_ITEM_INFO_1 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES BAG_ITEM_CATEGORY (
	CATEGORY_NO
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_EQUIPMENT_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO
);

ALTER TABLE EQUIPMENT ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_EQUIPMENT_2 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	CATEGORY_NO
);

ALTER TABLE ITEM_COMPATIBILITY ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_ITEM_COMPATIBILITY_1 FOREIGN KEY (
	ITEM_NO
)
REFERENCES BAG_ITEM_INFO (
	ITEM_NO
);

ALTER TABLE ITEM_COMPATIBILITY ADD CONSTRAINT FK_BAG_ITEM_INFO_TO_ITEM_COMPATIBILITY_2 FOREIGN KEY (
	CATEGORY_NO
)
REFERENCES BAG_ITEM_INFO (
	CATEGORY_NO
);

ALTER TABLE HERO_SKIN_INFO ADD CONSTRAINT FK_HERO_INFO_TO_HERO_SKIN_INFO_1 FOREIGN KEY (
	HERO_NO
)
REFERENCES HERO_INFO (
	HERO_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_LOG_GG_USER_TO_REPORT_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_BOARD_TO_REPORT_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE REPORT ADD CONSTRAINT FK_REPLY_TO_REPORT_1 FOREIGN KEY (
	REPLY_NO
)
REFERENCES REPLY (
	REPLY_NO
);

ALTER TABLE INQUIRY ADD CONSTRAINT FK_LOG_GG_USER_TO_INQUIRY_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);

ALTER TABLE CATEGORY_TABLE ADD CONSTRAINT FK_GAME_CODE_TO_CATEGORY_TABLE_1 FOREIGN KEY (
	GAME_CODE
)
REFERENCES GAME_CODE (
	GAME_CODE
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT FK_REPLY_TO_REPLY_LIKES_1 FOREIGN KEY (
	REPLY_NO
)
REFERENCES REPLY (
	REPLY_NO
);

ALTER TABLE REPLY_LIKES ADD CONSTRAINT FK_LOG_GG_USER_TO_REPLY_LIKES_1 FOREIGN KEY (
	USER_NO
)
REFERENCES LOG_GG_USER (
	USER_NO
);